version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/Lacajita/Adm-Caj"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    assignees: []
    reviewers: []
    commit-message:
      prefix: "chore(deps)"

  - package-ecosystem: "pip"
    directory: "/fastapi-playlists"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore(deps)"
