trigger:
  branches:
    include: [ main ]

pool:
  name: Default   # self-hosted

stages:
- stage: BuildAndTest
  displayName: Build and Test
  jobs:
  - job: Test
    displayName: Run tests on self-hosted agent
    steps:
    - script: |
        set -e
        VENV=/opt/azagent/venvs/py311
        if [ ! -x "$VENV/bin/python" ]; then
          echo "Venv no encontrado en $VENV. Provisiona pyenv/venv en el host."; exit 1
        fi
        echo "##vso[task.prependpath]$VENV/bin"
        python --version
      displayName: 'Use Python 3.11 (venv persistente)'

    - script: |
        set -e
        python -m pip install --upgrade pip wheel setuptools
        if [ -f requirements.txt ]; then python -m pip install -r requirements.txt; fi
      displayName: 'Install dependencies'

    - script: |
        set -e
        if [ -f tests/run_tests.py ]; then python tests/run_tests.py; else echo "No tests/run_tests.py"; fi
      displayName: 'Run tests (if present)'

- stage: Deploy
  displayName: Deploy
  dependsOn: BuildAndTest
  condition: succeeded()
  jobs:
  - job: DeployToHost
    displayName: Deploy to host
    steps:
    - script: |
        set -e
        VENV=/opt/azagent/venvs/py311
        echo "##vso[task.prependpath]$VENV/bin"
        python --version
      displayName: 'Ensure Python 3.11 venv'
    - script: |
        set -e
        chmod +x deploy/deploy_local.sh || true
        ./deploy/deploy_local.sh
      displayName: 'Run local deploy script'
