trigger:
  branches:
    include: [ main ]

pool:
  name: Default   # self-hosted

variables:
  pythonVersion: '3.12'

stages:
- stage: BuildAndTest
  displayName: Build and Test
  jobs:
  - job: Test
    displayName: Run tests on self-hosted agent
    steps:
    - script: |
        set -e
        if ! command -v python3.12 >/dev/null 2>&1; then
          echo "Python 3.12 no está instalado en el host"; exit 1
        fi
        python3.12 -m venv .venv
        echo "##vso[task.prependpath]$(System.DefaultWorkingDirectory)/.venv/bin"
        python --version
      displayName: 'Setup Python 3.12 (venv)'

    - script: |
        set -e
        python -m pip install --upgrade pip wheel setuptools
        if [ -f requirements.txt ]; then python -m pip install -r requirements.txt; fi
      displayName: 'Install dependencies'

    - script: |
        set -e
        if [ -f tests/run_tests.py ]; then python tests/run_tests.py; else echo "No tests/run_tests.py"; fi
      displayName: 'Run tests (if present)'

- stage: Deploy
  displayName: Deploy
  dependsOn: BuildAndTest
  condition: succeeded()
  jobs:
  - job: DeployToHost
    displayName: Deploy to host
    steps:
    - script: |
        set -e
        if [ ! -d ".venv" ]; then python3.12 -m venv .venv; fi
        echo "##vso[task.prependpath]$(System.DefaultWorkingDirectory)/.venv/bin"
        python --version
      displayName: 'Ensure Python 3.12 venv'
    - script: |
        set -e
        chmod +x deploy/deploy_local.sh || true
        ./deploy/deploy_local.sh
      displayName: 'Run local deploy script'
