name: Security Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  npm-audit:
    name: NPM Audit (frontend)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install frontend deps
        working-directory: Lacajita/Adm-Caj
        run: npm ci

      - name: Run npm audit
        working-directory: Lacajita/Adm-Caj
        run: npm audit --audit-level=low || true

  pip-audit:
    name: pip-audit (backend)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Create venv & install requirements
        working-directory: fastapi-playlists
        run: |
          python -m venv .venv
          . .venv/bin/activate
          pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt || true

      - name: Install pip-audit and run
        working-directory: fastapi-playlists
        run: |
          . .venv/bin/activate
          pip install pip-audit
          pip-audit || true
